import { PropertyStatus, PropertyType } from "./types";

export const APP_NAME = "Oman Royal Estates";
export const PRIMARY_COLOR_DARK = "royal-blue"; // Tailwind class name
export const PRIMARY_COLOR_LIGHT = "white";
export const ACCENT_COLOR = "gold-accent";

export const ROUTES = {
  HOME: '/',
  PROPERTIES: '/properties',
  PROPERTY_DETAIL: '/property', // e.g., /property/123
  FAVORITES: '/favorites',
  ALERTS: '/alerts', // Placeholder
  LOGIN: '/login', // Placeholder
  REGISTER: '/register', // Placeholder
  
  ABOUT_US: '/about-us',
  SERVICES: '/services',
  OUR_TEAM: '/our-team',
  CONTACT_US: '/contact-us',

  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    LISTINGS: '/admin/listings',
    EDIT_PROPERTY: '/admin/edit-property', // e.g., /admin/edit-property/123
    USERS: '/admin/users',
    CATEGORIES: '/admin/categories',
    CONTENT_PAGES: '/admin/content-pages',
    EDIT_CONTENT_PAGE: '/admin/edit-content', // e.g., /admin/edit-content/about-us
    HOME_SETTINGS: '/admin/home-settings', // New route for home page hero settings
  }
};

export const MAX_FEATURED_PROPERTIES = 6;
export const PROPERTIES_PER_PAGE = 9;

export const DEFAULT_CURRENCY = "OMR";

export const PROPERTY_STATUS_TRANSLATIONS: { [key in PropertyStatus]: string } = {
  [PropertyStatus.SALE]: 'للبيع',
  [PropertyStatus.RENT]: 'للإيجار',
  [PropertyStatus.OFF_PLAN]: 'على الخارطة',
};

export const PROPERTY_TYPE_TRANSLATIONS: { [key in PropertyType]: string } = {
  [PropertyType.APARTMENT]: 'شقة',
  [PropertyType.VILLA]: 'فيلا',
  [PropertyType.TOWNHOUSE]: 'تاون هاوس',
  [PropertyType.PENTHOUSE]: 'بنتهاوس',
  [PropertyType.LAND]: 'أرض',
  [PropertyType.OFFICE]: 'مكتب',
};

export const COMMON_TRANSLATIONS = {
  en: {
    home: 'Home',
    properties: 'Properties',
    forSale: 'For Sale',
    forRent: 'For Rent',
    offPlan: 'Off-Plan',
    company: 'Company',
    aboutUs: 'About Us',
    ourServices: 'Our Services',
    ourTeam: 'Our Team',
    contactUs: 'Contact Us',
    favorites: 'Favorites',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    welcome: 'Welcome',
    allProperties: 'All Properties',
    contactInfo: 'Contact Info',
    email: 'Email',
    phone: 'Phone',
    allRightsReserved: 'All rights reserved.',
    findYourDreamProperty: 'Find Your Dream Property in Oman',
    discoverExclusiveListings: `Discover exclusive listings for sale, rent, and off-plan projects with ${APP_NAME}.`,
    keywordOrLocation: 'Keyword or Location',
    searchPlaceholder: 'e.g., Villa, Muscat, Shatti Al Qurum',
    status: 'Status',
    anyStatus: 'Any Status',
    type: 'Type',
    anyType: 'Any Type',
    city: 'City',
    anyCity: 'Any City',
    search: 'Search',
    featuredProperties: 'Featured Properties',
    exploreFeatured: 'Explore a selection of our finest properties, handpicked for their quality and location.',
    viewAllProperties: 'View All Properties',
    whyChoose: `Why Choose ${APP_NAME}?`,
    whyChooseDesc: `We offer a curated selection of Oman's finest real estate, backed by expert advice and a seamless user experience. Whether buying, selling, or renting, we are your dedicated partners.`,
    expertKnowledge: 'Expert Market Knowledge',
    expertKnowledgeDesc: 'Deep insights into the Omani property market to guide your decisions.',
    premiumListings: 'Premium Listings',
    premiumListingsDesc: 'Access to exclusive villas, apartments, and off-plan projects.',
    personalizedService: 'Personalized Service',
    personalizedServiceDesc: 'Dedicated support to help you find the perfect property.',
    filterProperties: 'Filter Properties',
    priceRange: `Price Range (${DEFAULT_CURRENCY})`,
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    sizeSqft: 'Size (sqft)',
    minSize: 'Min Size',
    maxSize: 'Max Size',
    bedrooms: 'Bedrooms',
    any: 'Any',
    amenities: 'Amenities',
    applyFilters: 'Apply Filters',
    resetFilters: 'Reset Filters',
    showFilters: 'Show Filters',
    hideFilters: 'Hide Filters',
    findYourProperty: 'Find Your Property',
    browseAndFilterProperties: 'Browse our extensive collection and use the filters to find exactly what you\'re looking for.', // New
    showingProperties: 'Showing {count} of {total} properties.',
    noPropertiesFound: 'No Properties Found',
    tryAdjustingFilters: 'Try adjusting your search or filter criteria.',
    backToListings: '← Back to listings',
    favorite: 'Favorite',
    favorited: 'Favorited',
    share: 'Share',
    price: 'Price',
    perMonth: '/month',
    beds: 'Beds',
    bed: 'Bed',
    baths: 'Baths',
    bath: 'Bath',
    areaSqft: 'Area (sqft)',
    parking: 'Parking',
    listedOn: 'Listed On',
    propertyDescription: 'Property Description',
    floorPlan: 'Floor Plan',
    location: 'Location',
    contactAgent: 'Contact Agent',
    messageOnWhatsApp: 'Message on WhatsApp',
    callAgent: 'Call Agent',
    requestDetails: 'Request Details / Book Viewing',
    added: 'Added',
    myFavoriteProperties: 'My Favorite Properties',
    noFavoritesYet: 'No Favorites Yet',
    noFavoritesDesc: "You haven't added any properties to your favorites. Start browsing to find your dream property!",
    browseProperties: 'Browse Properties',
    loading: 'Loading...',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    // Admin specific
    adminDashboard: 'Admin Dashboard',
    adminWelcome: 'Welcome to the admin area. From here, you can manage listings, users, categories, and other site settings.',
    adminNotePlaceholder: 'Note: This is a placeholder page. Full admin functionality would require backend integration and proper state management for edits.',
    manageListings: 'Manage Listings',
    manageListingsDesc: 'Create, edit, and delete property listings.',
    manageUsers: 'Manage Users',
    manageUsersDesc: 'View and manage user accounts and permissions.',
    manageCategories: 'Manage Categories',
    manageCategoriesDesc: 'Manage property types, cities, and amenities.',
    manageContentPages: 'Manage Content Pages',
    manageContentPagesDesc: 'Edit content for About Us, Services, etc.',
    featuredPropertiesAdmin: 'Featured Properties',
    featuredPropertiesAdminDesc: 'Manage homepage sections (Not Implemented).',
    backToDashboard: '← Back to Dashboard',
    createNewListing: '+ Create New Listing',
    manageListingsInstructions: 'Below is a list of all properties. Click "Edit" to modify their details or "Delete" to remove them.',
    adminClientSideNote: '(Note: Changes are client-side and won\'t persist after page reload in this demo.)',
    titleLabel: 'Title',
    cityLabel: 'City',
    statusLabel: 'Status',
    priceLabel: 'Price',
    agentPhoneLabel: 'Agent Phone',
    actionsLabel: 'Actions',
    editPropertyTitle: 'Edit Property: {title}',
    createNewPropertyTitle: 'Create New Property',
    basicInformationLegend: 'Basic Information',
    propertyTypeLabel: 'Property Type',
    descriptionLabel: 'Description',
    priceSizeLegend: 'Price & Size',
    priceOMRLabel: 'Price (OMR)',
    sizeSqftLabel: 'Size (sqft)',
    specificationsLegend: 'Specifications',
    bedroomsLabel: 'Bedrooms',
    bathroomsLabel: 'Bathrooms',
    parkingSpacesLabel: 'Parking Spaces',
    amenitiesLegend: 'Amenities',
    mediaLegend: 'Media',
    galleryUrlsLabel: 'Gallery Image URLs (comma-separated)',
    galleryUrlsPlaceholder: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
    floorPlanUrlLabel: 'Floor Plan Image URL',
    floorPlanUrlPlaceholder: 'https://example.com/floorplan.jpg',
    locationLegend: 'Location',
    fullAddressLabel: 'Full Address',
    latitudeLabel: 'Latitude',
    longitudeLabel: 'Longitude',
    agentDetailsLegend: 'Agent Details',
    agentNameLabel: 'Agent Name',
    agentEmailLabel: 'Agent Email',
    otherSettingsLegend: 'Other Settings',
    isFeaturedQuestion: 'Is this a Featured Property?',
    idLabel: 'ID',
    addedDateLabel: 'Added',
    createPropertyButton: 'Create Property',
    savingButton: 'Saving...',
    creatingButton: 'Creating...',
    confirmDeleteProperty: 'Are you sure you want to delete this property? This action cannot be undone.',
    propertyDeletedSuccess: 'Property deleted successfully.',
    propertyDeletedFailed: 'Failed to delete property.',
    propertyCreatedSuccess: 'Property created successfully! (Client-side mock)',
    propertyUpdatedSuccess: 'Property updated successfully! (Client-side mock)',
    propertyUpdateError: 'Error updating property.',
    loadingPropertyEditor: 'Loading property editor...',
    propertyNotFoundForEditing: 'Property with ID "{propertyId}" not found for editing.',
    manageContentPagesTitle: 'Manage Content Pages',
    manageContentPagesInstructions: 'Below is a list of manageable content pages. Click "Edit" to modify their content.',
    adminContentEditingNote: '(Note: Editing functionality is a placeholder and won\'t persist changes yet.)',
    pageTitleLabel: 'Page Title',
    slugLabel: 'Slug',
    lastUpdatedLabel: 'Last Updated',
    viewLivePage: 'View Live Page',
    editContentPageTitle: 'Edit: {title}',
    backToContentPages: '← Back to Content Pages',
    loadingPageEditor: 'Loading page editor...',
    contentPageNotFound: 'Content page with slug "{pageSlug}" not found.',
    manageTeamMembers: 'Manage Team Members',
    addNewMember: '+ Add New Member',
    confirmDeleteTeamMember: 'Are you sure you want to delete this team member?',
    teamMemberDeleted: 'Team member deleted.',
    noTeamMembersFound: 'No team members found. Click "Add New Member" to get started.',
    editPageIntroConclusion: 'Edit Page Introduction/Conclusion',
    pageIntroContentHelpText: 'Use \'\\n\' for new paragraphs if simple text. This content will appear above/below the team member list on the public page.',
    pageContentLabel: 'Page Content',
    pageContentPlaceholder: 'Enter page content here...',
    savePageTextChanges: 'Save Page Text Changes',
    currentVersionLastUpdated: 'Current version last updated: {date}',
    editTeamMemberModalTitle: 'Edit Team Member',
    addTeamMemberModalTitle: 'Add New Team Member',
    nameRequiredError: 'Name and Title are required.',
    photoUrlInvalidError: 'Photo URL must be a valid URL (e.g., https://...).',
    nameLabel: 'Name*',
    roleLabel: 'Title/Role*',
    photoUrlLabel: 'Photo URL',
    bioLabel: 'Short Bio/Specialty',
    linkedinUrlLabel: 'LinkedIn Profile URL',
    linkedinUrlPlaceholder: 'https://linkedin.com/in/...',
    instagramUrlLabel: 'Instagram Profile URL',
    instagramUrlPlaceholder: 'https://instagram.com/...',
    genericSaveSuccess: 'Placeholder: Generic content saved!\n(Changes are mock and client-side.)',
    pageInfoLastUpdated: 'Page information last updated: {date}',
    contentNotAvailable: 'Content for this page is not available at the moment.',
    serviceInfoNotAvailable: 'Service information is not available at the moment.',
    teamInfoNotAvailable: 'Team information is not available at the moment.',
    loginToAccount: 'Login to Your Account',
    createAnAccount: 'Create an Account',
    emailAddressLabel: 'Email Address',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    unexpectedError: 'An unexpected error occurred.',
    loggingIn: 'Logging in...',
    registering: 'Registering...',
    processing: 'Processing...',
    dontHaveAccount: "Don't have an account?",
    registerHere: 'Register here',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    pageNotFoundTitle: '404 - Not Found',
    pageNotFoundMessage: 'The page you are looking for does not exist.',
    goToHomepage: 'Go to Homepage',
    noFeaturedProperties: 'No featured properties available at the moment.',
    contactFormGetInTouch: 'Get in Touch',
    contactFormSendUsMessage: 'Send Us a Message',
    contactFormFullName: 'Full Name',
    contactFormSubject: 'Subject',
    contactFormMessage: 'Message',
    contactFormSendMessage: 'Send Message',
    contactFormSubmitted: 'Thank you for your message! We will get back to you shortly.',
    contactFormAddressPlaceholder: '[Street Address], [City], Muscat, Oman',
    alertLoginToFavorite: "Please login to add properties to your favorites.",
    alertLinkCopied: "Link copied to clipboard!",
    alertCouldNotCopyLink: "Could not copy link.",
    propertyNotFound: "Property not found.",
    switchLanguageToArabic: "Switch to Arabic",
    switchLanguageToEnglish: "Switch to English",
    openMainMenu: "Open main menu",
    featuredTag: "FEATURED",
    arAppName: "عقارات عمان الملكية",
    // New Hero Settings translations
    manageHomePageHero: "Manage Home Page Hero",
    manageHomePageHeroDesc: "Customize the main banner image or video on the home page.",
    homePageHeroSettingsTitle: "Home Page Hero Settings",
    mediaTypeLabel: "Media Type",
    imageTypeLabel: "Image",
    videoTypeLabel: "Video",
    mediaUrlLabel: "Media URL",
    imageUrlLabel: "Image URL",
    videoUrlLabel: "Video URL",
    mediaUrlPlaceholderImage: "https://example.com/hero-image.jpg",
    mediaUrlPlaceholderVideo: "https://example.com/hero-video.mp4",
    currentPreviewLabel: "Current Preview",
    fallbackImageUrlLabel: "Fallback Image URL (Poster for Video)",
    fallbackImageUrlPlaceholder: "https://example.com/fallback-image.jpg",
    heroSettingsUpdatedSuccess: "Home page hero settings updated successfully! (Client-side mock)",
    invalidUrlError: "Please enter a valid URL.",
    searchProperties: "Search Properties",
    generateWithAI_EN: "Generate with AI (EN)",
    generateWithAI_AR: "Generate with AI (AR)",
    generatingDescription: "Generating description...",
    aiGenerationError: "AI generation failed. Please try again or write manually.",
  },
  ar: {
    home: 'الرئيسية',
    properties: 'العقارات',
    forSale: 'للبيع',
    forRent: 'للإيجار',
    offPlan: 'على الخارطة',
    company: 'الشركة',
    aboutUs: 'معلومات عنا',
    ourServices: 'خدماتنا',
    ourTeam: 'فريقنا',
    contactUs: 'اتصل بنا',
    favorites: 'المفضلة',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً',
    allProperties: 'جميع العقارات',
    contactInfo: 'معلومات الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    findYourDreamProperty: 'ابحث عن عقار أحلامك في عمان',
    discoverExclusiveListings: `اكتشف قوائم حصرية للبيع والإيجار ومشاريع على الخارطة مع ${APP_NAME}.`, // APP_NAME will be replaced by appDisplayName in components
    keywordOrLocation: 'كلمة مفتاحية أو موقع',
    searchPlaceholder: 'مثال: فيلا، مسقط، شاطئ القرم',
    status: 'الحالة',
    anyStatus: 'أي حالة',
    type: 'النوع',
    anyType: 'أي نوع',
    city: 'المدينة',
    anyCity: 'أي مدينة',
    search: 'بحث',
    featuredProperties: 'العقارات المميزة',
    exploreFeatured: 'استكشف مجموعة مختارة من أرقى عقاراتنا، المختارة بعناية لجودتها وموقعها.',
    viewAllProperties: 'عرض جميع العقارات',
    whyChoose: `لماذا تختار ${APP_NAME}؟`, // APP_NAME will be replaced
    whyChooseDesc: 'نقدم مجموعة منسقة من أرقى العقارات في عمان، مدعومة بخبرة متخصصة وتجربة مستخدم سلسة. سواء كنت تشتري أو تبيع أو تستأجر، نحن شركاؤك المخلصون.',
    expertKnowledge: 'معرفة سوقية متخصصة',
    expertKnowledgeDesc: 'رؤى عميقة حول سوق العقارات العماني لتوجيه قراراتك.',
    premiumListings: 'قوائم عقارية متميزة',
    premiumListingsDesc: 'الوصول إلى الفلل والشقق والمشاريع الحصرية على الخارطة.',
    personalizedService: 'خدمة شخصية',
    personalizedServiceDesc: 'دعم مخصص لمساعدتك في العثور على العقار المثالي.',
    filterProperties: 'تصفية العقارات',
    priceRange: `نطاق السعر (${DEFAULT_CURRENCY})`,
    minPrice: 'أقل سعر',
    maxPrice: 'أعلى سعر',
    sizeSqft: 'المساحة (قدم مربع)',
    minSize: 'أقل مساحة',
    maxSize: 'أقصى مساحة',
    bedrooms: 'غرف النوم',
    any: 'الكل',
    amenities: 'المرافق',
    applyFilters: 'تطبيق الفلاتر',
    resetFilters: 'إعادة تعيين الفلاتر',
    showFilters: 'إظهار الفلاتر',
    hideFilters: 'إخفاء الفلاتر',
    findYourProperty: 'ابحث عن عقارك',
    browseAndFilterProperties: 'تصفح مجموعتنا الواسعة واستخدم الفلاتر للعثور على ما تبحث عنه بالضبط.', // New
    showingProperties: 'عرض {count} من {total} عقارات.',
    noPropertiesFound: 'لم يتم العثور على عقارات',
    tryAdjustingFilters: 'حاول تعديل معايير البحث أو التصفية.',
    backToListings: '→ العودة إلى القائمة',
    favorite: 'إضافة للمفضلة',
    favorited: 'في المفضلة',
    share: 'مشاركة',
    price: 'السعر',
    perMonth: '/شهرياً',
    beds: 'غرف نوم',
    bed: 'غرفة نوم',
    baths: 'حمامات',
    bath: 'حمام',
    areaSqft: 'المساحة (قدم مربع)',
    parking: 'مواقف السيارات',
    listedOn: 'أضيف بتاريخ',
    propertyDescription: 'وصف العقار',
    floorPlan: 'مخطط الطابق',
    location: 'الموقع',
    contactAgent: 'اتصل بالوكيل',
    messageOnWhatsApp: 'رسالة عبر واتساب',
    callAgent: 'اتصل بالوكيل',
    requestDetails: 'طلب تفاصيل / حجز معاينة',
    added: 'أضيف',
    myFavoriteProperties: 'عقاراتي المفضلة',
    noFavoritesYet: 'لا توجد عقارات مفضلة بعد',
    noFavoritesDesc: 'لم تقم بإضافة أي عقارات إلى مفضلتك. ابدأ التصفح للعثور على عقار أحلامك!',
    browseProperties: 'تصفح العقارات',
    loading: 'جار التحميل...',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    // Admin specific
    adminDashboard: 'لوحة تحكم المسؤول',
    adminWelcome: 'مرحباً بك في منطقة المسؤول. من هنا، يمكنك إدارة القوائم والمستخدمين والفئات وإعدادات الموقع الأخرى.',
    adminNotePlaceholder: 'ملاحظة: هذه صفحة نائبة. تتطلب وظائف المسؤول الكاملة تكامل الواجهة الخلفية وإدارة الحالة المناسبة للتعديلات.',
    manageListings: 'إدارة القوائم العقارية',
    manageListingsDesc: 'إنشاء وتعديل وحذف القوائم العقارية.',
    manageUsers: 'إدارة المستخدمين',
    manageUsersDesc: 'عرض وإدارة حسابات المستخدمين والأذونات.',
    manageCategories: 'إدارة الفئات',
    manageCategoriesDesc: 'إدارة أنواع العقارات والمدن والمرافق.',
    manageContentPages: 'إدارة صفحات المحتوى',
    manageContentPagesDesc: 'تعديل محتوى صفحات مثل "معلومات عنا"، "خدماتنا"، إلخ.',
    featuredPropertiesAdmin: 'العقارات المميزة',
    featuredPropertiesAdminDesc: 'إدارة أقسام الصفحة الرئيسية (غير منفذة).',
    backToDashboard: '→ العودة إلى لوحة التحكم',
    createNewListing: '+ إنشاء قائمة جديدة',
    manageListingsInstructions: 'أدناه قائمة بجميع العقارات. انقر على "تعديل" لتعديل تفاصيلها أو "حذف" لإزالتها.',
    adminClientSideNote: '(ملاحظة: التغييرات على جانب العميل ولن تستمر بعد إعادة تحميل الصفحة في هذا العرض التوضيحي.)',
    titleLabel: 'العنوان',
    cityLabel: 'المدينة',
    statusLabel: 'الحالة',
    priceLabel: 'السعر',
    agentPhoneLabel: 'هاتف الوكيل',
    actionsLabel: 'الإجراءات',
    editPropertyTitle: 'تعديل العقار: {title}',
    createNewPropertyTitle: 'إنشاء عقار جديد',
    basicInformationLegend: 'المعلومات الأساسية',
    propertyTypeLabel: 'نوع العقار',
    descriptionLabel: 'الوصف',
    priceSizeLegend: 'السعر والمساحة',
    priceOMRLabel: 'السعر (ريال عماني)',
    sizeSqftLabel: 'المساحة (قدم مربع)',
    specificationsLegend: 'المواصفات',
    bedroomsLabel: 'غرف النوم',
    bathroomsLabel: 'الحمامات',
    parkingSpacesLabel: 'مواقف السيارات',
    amenitiesLegend: 'المرافق',
    mediaLegend: 'الوسائط',
    galleryUrlsLabel: 'روابط صور المعرض (مفصولة بفواصل)',
    galleryUrlsPlaceholder: 'https://example.com/image1.jpg, https://example.com/image2.jpg',
    floorPlanUrlLabel: 'رابط صورة مخطط الطابق',
    floorPlanUrlPlaceholder: 'https://example.com/floorplan.jpg',
    locationLegend: 'الموقع',
    fullAddressLabel: 'العنوان الكامل',
    latitudeLabel: 'خط العرض',
    longitudeLabel: 'خط الطول',
    agentDetailsLegend: 'تفاصيل الوكيل',
    agentNameLabel: 'اسم الوكيل',
    agentEmailLabel: 'بريد الوكيل الإلكتروني',
    otherSettingsLegend: 'إعدادات أخرى',
    isFeaturedQuestion: 'هل هذا عقار مميز؟',
    idLabel: 'المعرف',
    addedDateLabel: 'أضيف بتاريخ',
    createPropertyButton: 'إنشاء عقار',
    savingButton: 'جاري الحفظ...',
    creatingButton: 'جاري الإنشاء...',
    confirmDeleteProperty: 'هل أنت متأكد أنك تريد حذف هذا العقار؟ لا يمكن التراجع عن هذا الإجراء.',
    propertyDeletedSuccess: 'تم حذف العقار بنجاح.',
    propertyDeletedFailed: 'فشل حذف العقار.',
    propertyCreatedSuccess: 'تم إنشاء العقار بنجاح! (محاكاة على جانب العميل)',
    propertyUpdatedSuccess: 'تم تحديث العقار بنجاح! (محاكاة على جانب العميل)',
    propertyUpdateError: 'خطأ في تحديث العقار.',
    loadingPropertyEditor: 'جاري تحميل محرر العقار...',
    propertyNotFoundForEditing: 'لم يتم العثور على العقار بالمعرف "{propertyId}" للتعديل.',
    manageContentPagesTitle: 'إدارة صفحات المحتوى',
    manageContentPagesInstructions: 'أدناه قائمة بصفحات المحتوى القابلة للإدارة. انقر على "تعديل" لتعديل محتواها.',
    adminContentEditingNote: '(ملاحظة: وظيفة التعديل هي نائبة ولن تحتفظ بالتغييرات بعد.)',
    pageTitleLabel: 'عنوان الصفحة',
    slugLabel: 'المعرف الفريد (Slug)',
    lastUpdatedLabel: 'آخر تحديث',
    viewLivePage: 'عرض الصفحة مباشرة',
    editContentPageTitle: 'تعديل: {title}',
    backToContentPages: '→ العودة إلى صفحات المحتوى',
    loadingPageEditor: 'جاري تحميل محرر الصفحة...',
    contentPageNotFound: 'لم يتم العثور على صفحة المحتوى بالمعرف الفريد "{pageSlug}".',
    manageTeamMembers: 'إدارة أعضاء الفريق',
    addNewMember: '+ إضافة عضو جديد',
    confirmDeleteTeamMember: 'هل أنت متأكد أنك تريد حذف عضو الفريق هذا؟',
    teamMemberDeleted: 'تم حذف عضو الفريق.',
    noTeamMembersFound: 'لم يتم العثور على أعضاء فريق. انقر على "إضافة عضو جديد" للبدء.',
    editPageIntroConclusion: 'تعديل مقدمة/خاتمة الصفحة',
    pageIntroContentHelpText: 'استخدم "\\n" لفقرات جديدة إذا كان النص بسيطًا. سيظهر هذا المحتوى أعلى/أسفل قائمة أعضاء الفريق في الصفحة العامة.',
    pageContentLabel: 'محتوى الصفحة',
    pageContentPlaceholder: 'أدخل محتوى الصفحة هنا...',
    savePageTextChanges: 'حفظ تغييرات نص الصفحة',
    currentVersionLastUpdated: 'آخر تحديث للنسخة الحالية: {date}',
    editTeamMemberModalTitle: 'تعديل عضو الفريق',
    addTeamMemberModalTitle: 'إضافة عضو فريق جديد',
    nameRequiredError: 'الاسم والمنصب مطلوبان.',
    photoUrlInvalidError: 'رابط الصورة يجب أن يكون رابطًا صالحًا (مثال: https://...).',
    nameLabel: 'الاسم*',
    roleLabel: 'المنصب/الدور*',
    photoUrlLabel: 'رابط الصورة',
    bioLabel: 'نبذة تعريفية/تخصص مختصر',
    linkedinUrlLabel: 'رابط ملف لينكدإن',
    linkedinUrlPlaceholder: 'https://linkedin.com/in/...',
    instagramUrlLabel: 'رابط ملف انستغرام',
    instagramUrlPlaceholder: 'https://instagram.com/...',
    genericSaveSuccess: 'نائب: تم حفظ المحتوى العام!\n(التغييرات هي محاكاة وعلى جانب العميل.)',
    pageInfoLastUpdated: 'آخر تحديث لمعلومات الصفحة: {date}',
    contentNotAvailable: 'المحتوى لهذه الصفحة غير متوفر حاليًا.',
    serviceInfoNotAvailable: 'معلومات الخدمة غير متوفرة حاليًا.',
    teamInfoNotAvailable: 'معلومات الفريق غير متوفرة حاليًا.',
    loginToAccount: 'تسجيل الدخول إلى حسابك',
    createAnAccount: 'إنشاء حساب جديد',
    emailAddressLabel: 'عنوان البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة.',
    unexpectedError: 'حدث خطأ غير متوقع.',
    loggingIn: 'جاري تسجيل الدخول...',
    registering: 'جاري التسجيل...',
    processing: 'جاري المعالجة...',
    dontHaveAccount: "ليس لديك حساب؟",
    registerHere: 'سجل هنا',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    loginHere: 'سجل الدخول هنا',
    pageNotFoundTitle: '404 - الصفحة غير موجودة',
    pageNotFoundMessage: 'الصفحة التي تبحث عنها غير موجودة.',
    goToHomepage: 'الذهاب إلى الصفحة الرئيسية',
    noFeaturedProperties: 'لا توجد عقارات مميزة متاحة في الوقت الحالي.',
    contactFormGetInTouch: 'تواصل معنا',
    contactFormSendUsMessage: 'أرسل لنا رسالة',
    contactFormFullName: 'الاسم الكامل',
    contactFormSubject: 'الموضوع',
    contactFormMessage: 'الرسالة',
    contactFormSendMessage: 'إرسال الرسالة',
    contactFormSubmitted: 'شكرا لرسالتك! سوف نعود اليك قريبا.',
    contactFormAddressPlaceholder: '[عنوان الشارع]، [المدينة]، مسقط، عمان',
    alertLoginToFavorite: "الرجاء تسجيل الدخول لإضافة العقارات إلى المفضلة.",
    alertLinkCopied: "تم نسخ الرابط إلى الحافظة!",
    alertCouldNotCopyLink: "لا يمكن نسخ الرابط.",
    propertyNotFound: "العقار غير موجود.",
    switchLanguageToArabic: "التحويل إلى العربية",
    switchLanguageToEnglish: "التحويل إلى الإنجليزية",
    openMainMenu: "فتح القائمة الرئيسية",
    featuredTag: "مميز",
    arAppName: "عقارات عمان الملكية",
    // New Hero Settings translations
    manageHomePageHero: "إدارة بانر الصفحة الرئيسية",
    manageHomePageHeroDesc: "تخصيص الصورة أو الفيديو الرئيسي في بانر الصفحة الرئيسية.",
    homePageHeroSettingsTitle: "إعدادات بانر الصفحة الرئيسية",
    mediaTypeLabel: "نوع الوسائط",
    imageTypeLabel: "صورة",
    videoTypeLabel: "فيديو",
    mediaUrlLabel: "رابط الوسائط",
    imageUrlLabel: "رابط الصورة",
    videoUrlLabel: "رابط الفيديو",
    mediaUrlPlaceholderImage: "https://example.com/hero-image.jpg",
    mediaUrlPlaceholderVideo: "https://example.com/hero-video.mp4",
    currentPreviewLabel: "المعاينة الحالية",
    fallbackImageUrlLabel: "رابط الصورة الاحتياطية (بوستر للفيديو)",
    fallbackImageUrlPlaceholder: "https://example.com/fallback-image.jpg",
    heroSettingsUpdatedSuccess: "تم تحديث إعدادات بانر الصفحة الرئيسية بنجاح! (محاكاة من جانب العميل)",
    invalidUrlError: "الرجاء إدخال رابط صحيح.",
    searchProperties: "بحث العقارات",
    generateWithAI_EN: "إنشاء بواسطة الذكاء الاصطناعي (EN)",
    generateWithAI_AR: "إنشاء بواسطة الذكاء الاصطناعي (AR)",
    generatingDescription: "جاري إنشاء الوصف...",
    aiGenerationError: "فشل إنشاء الوصف بواسطة الذكاء الاصطناعي. يرجى المحاولة مرة أخرى أو الكتابة يدويًا.",
  }
};